### PR TITLE
Add cache

### PR DESCRIPTION
**Pull request by hieudole**

### CODE REVIEW

**Comment by jstemerdink** [comment]
Isn't this a bit much? Why a whole custom cachemanager implementation? Why not use the default Episerver options Like the event service and a custom raiser and event id?

**Comment by LinusEkstrom** [comment]
I agree - I asked Hieu to help and the idea was to use the default Episerver cache manager - so this should be simplified. I'll try to find an example of how this is normally done...

**Comment by jstemerdink** [comment]
I had to do something similar with my localization provider, maybe [this](https://github.com/jstemerdink/EPi.Libraries.Localization/blob/master/EPi.Libraries.Localization/TranslationProviderInitialization.cs) is a good reference?  I can see if I make some time, but am not sure when, as I am kinda swamped at the moment

**Comment by hieudole** [comment]
#15

**Comment by LinusEkstrom** [comment]
Here's a code sample of how Episervers DefaultContentType lists uses the ISynchronizedObjectInstanceCache:

private ISynchronizedObjectInstanceCache _cacheInstance;

private IEnumerable<ContentType> GetMergedList()
	{
		List<ContentType> list = _cacheInstance.Get("EP:ListContentType") as List<ContentType>;
		if (list != null)
		{
			return list;
		}
		lock (_lockObject)
		{
			list = (_cacheInstance.Get("EP:ListContentType") as List<ContentType>);
			if (list == null)
			{
				list = new List<ContentType>();
				foreach (ContentType item in _contentTypeDB.List())
				{
					string instanceCacheKey = GetInstanceCacheKey(item.ID);
					ContentType contentType = _cacheInstance.Get(instanceCacheKey) as ContentType;
					if (contentType == (ContentType)null)
					{
						contentType = (item.CreateWritableClone() as ContentType);
						MergeModelAndProperties(contentType);
						contentType.MakeReadOnly();
						AddToInstanceCache(contentType, null);
					}
					list.Add(contentType);
				}
				list.Sort((ContentType x, ContentType y) => x.SortOrder.CompareTo(y.SortOrder));
				_cacheInstance.Insert("EP:ListContentType", list, new CacheEvictionPolicy(null, new string[1]
				{
					"EP:MasterContentType"
				}));
				return list;
			}
			return list;
		}
	}

public static void ClearCache()
	{
		ClearMergedModelsFromCache();
		ContentTypeDB.ClearCache();
	}

	internal static void ClearMergedModelsFromCache()
	{
		CacheManager.Remove("EP:MasterContentType");
	}

**Comment by LinusEkstrom** [comment]
This has been replaced by another PR that solves the same issue.

**Pull request closed without merging**
